# Generated by Django 6.0.5 on 2026-07-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_group_customuser_groups_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('reader', 'Reader')], default='reader', max_length=20),
        ),
    ]
